### PR TITLE
Write out multiple conformers

### PR DESCRIPTION
**Pull request by ChayaSt**
I added an option to write out all conformers in a multiconformer molecule to mol2 file.

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
From what I can tell, this looks great.

Could you add a test (like the test I link below) that uses the new option for a molecule with more than one conformer? Adding a test will prevent someone else from breaking the feature you need in the future. 

https://github.com/choderalab/openmoltools/blob/master/openmoltools/tests/test_openeye.py#L65

You can probably just check that you get more than one match for the string `@<TRIPOS>MOLECULE`, if you read the output file back in as text.

**Comment by ChayaSt** [comment]
> You can probably just check that you get more than one match for the string @<TRIPOS>MOLECULE, if you read the output file back in as text.

Thanks! I added such a test.

**Comment by ChayaSt** [comment]
@bas-rustenburg, ready to merge?

**Comment by Lnaden** [comment]
Just a small check, it will be okay that this bugfix/change will not be available in Python 2.7?

**Comment by ChayaSt** [comment]
@Lnaden, I'm not supporting Python 2.7 so it shouldn't be a problem.

**Comment by Lnaden** [comment]
Go for it then!

**Pull request merged**
