### PR TITLE
Automated resname randomization

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
I'm still fixing a bug in this, but should be done soonish.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Ah, OK, so you're ahead of me. Nice! Here I was thinking that since there was no response I should get cracking on it. Thanks for your help. I am SO excited about how smoothly setup of stuff is going to go moving on from here. It feels like the invention of the wheel. ;)

**Comment by davidlmobley** [comment]
@kyleabeauchamp - I'm slightly confused about the timing of things, as your remark says you're still fixing a bug. So if I understand right this is NOT ready for me to test/look at yet?

**Comment by kyleabeauchamp** [comment]
Correct, we generally mark things as "Work in Progress" [WIP] when there's still coding to be done.

**Comment by davidlmobley** [comment]
I have some time this afternoon prior to 3 pm Pacific/6 Eastern. Is there anything I can help with to finish this off? (This is sort of the "next step" needed for a couple efforts in my group.)

**Comment by davidlmobley** [comment]
Ah, my comment crossed with your commit. Looks like you're still moving. Regardless let me know if there's anything I can help with.

**Comment by kyleabeauchamp** [comment]
So AFAIK this is now working, but it relies on having the very most recent version of Parmed (https://github.com/ParmEd/ParmEd/pull/128) installed.  

To get a feel for the proposed workflow, you can look at the new test `test_binary_mixture_rename()` in the diff.

Let me know if this doesn't work for you, and I can help you write an improved version.

**Comment by kyleabeauchamp** [comment]
I also considered other workflows, but ran into trouble getting OE to spit out gaff-compatible mol2 filenames.  I imagine you and other folks know how to do that, so that would be another option here.

**Comment by kyleabeauchamp** [comment]
Sigh, still fixing one last issue:

```
nosetests openmoltools -v --exe -a 'parmed'

[...]

Bond: Maximum coordination exceeded on .R<ZFR 1>.A<H14 23>
      -- setting atoms pert=true overrides default limits
ATOMS NOT BONDED: .R<ZFR 1>.A<C6 6> .R<ZFR 1>.A<H14 23>
!FATAL ERROR----------------------------------------
!FATAL:    In file [atom.c], line 445
!FATAL:    Message: bondAtomProblem found
!
!ABORTING.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.978s
```

**Comment by davidlmobley** [comment]
Sorry, what do you mean by GAFF-compatible mol2 filenames? I was not aware
GAFF had filename constraints? (Are you talking about
Antechamber-compatible? And what compatibility issues did you run into?)

On Fri, May 1, 2015 at 12:06 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> I also considered other workflows, but ran into trouble getting OE to spit
> out gaff-compatible mol2 filenames. I imagine you and other folks know how
> to do that, so that would be another option here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/pull/104#issuecomment-98207490>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by kyleabeauchamp** [comment]
OK, everything here should be fixed now.  There was a very tricky bug `build-mixture_prmtop()` where the residue names were being converted from a list into a set and then back, which caused sporadic swapping of the order.  This is now fixed.

**Comment by davidlmobley** [comment]
Thanks. I'll test. Can you clarify the issue about GAFF-compatible mol2
filenames? I'm still uncertain why ParmEd is needed rather than just using
OEChem to modify the residue name in the mol2, though I'm OK with it being
used (it's easy to install).

On Fri, May 1, 2015 at 1:06 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> OK, everything here should be fixed now. There was a very tricky bug
> build-mixture_prmtop() where the residue names were being converted from
> a list into a set and then back, which caused sporadic swapping of the
> order. This is now fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/pull/104#issuecomment-98221465>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by kyleabeauchamp** [comment]
Here's what I'm talking about--the atom types in the below output.   It's probably a simple fix, so we can make a separate PR to fix this if desired.

```
wget https://raw.githubusercontent.com/choderalab/openmoltools/master/openmoltools/chemicals/etoh/etoh.mol2

import openeye.oechem as oechem
import openmoltools

ifs = oechem.oemolistream()
ifs.open("etoh.mol2")

for molecule in ifs.GetOEMols():
    break
    
openmoltools.openeye.molecule_to_mol2(molecule, "./out.mol2")


kyleb@kyleb-DX4870:~/src/kyleabeauchamp/openmoltools/tmp/etoh$ cat etoh.mol2 
@<TRIPOS>MOLECULE
LIG
    9     8     1     0     0
SMALL
bcc


@<TRIPOS>ATOM
      1 O          -1.1710    0.3000    0.0000 oh        1 LIG     -0.599800
      2 C          -0.0460   -0.5670    0.0000 c3        1 LIG      0.126400
      3 C1          1.2180    0.2670    0.0000 c3        1 LIG     -0.136100
      4 H          -0.0960   -1.2120    0.8820 h1        1 LIG      0.043200
      5 H1         -0.0950   -1.1940   -0.8950 h1        1 LIG      0.043200
      6 H2          2.1050   -0.3720   -0.0180 hc        1 LIG      0.042367
      7 H3          1.2430    0.9310   -0.8700 hc        1 LIG      0.042367
      8 H4          1.2620    0.9050    0.8890 hc        1 LIG      0.042367
      9 H5         -1.1290    0.8360    0.8100 ho        1 LIG      0.396000
@<TRIPOS>BOND
     1    1    2 1   
     2    1    9 1   
     3    2    3 1   
     4    2    4 1   
     5    2    5 1   
     6    3    6 1   
     7    3    7 1   
     8    3    8 1   
@<TRIPOS>SUBSTRUCTURE
     1 LIG         1 TEMP              0 ****  ****    0 ROOT
kyleb@kyleb-DX4870:~/src/kyleabeauchamp/openmoltools/tmp/etoh$ cat out.mol2 
@<TRIPOS>MOLECULE
LIG
    9     8     0     0     0
SMALL
USER_CHARGES

@<TRIPOS>ATOM
      1 O1         -1.1710    0.3000    0.0000 O.3       1 MOL        -0.5998
      2 C1         -0.0460   -0.5670    0.0000 C.3       1 MOL         0.1264
      3 C2          1.2180    0.2670    0.0000 C.3       1 MOL        -0.1361
      4 H1         -0.0960   -1.2120    0.8820 H         1 MOL         0.0432
      5 H2         -0.0950   -1.1940   -0.8950 H         1 MOL         0.0432
      6 H3          2.1050   -0.3720   -0.0180 H         1 MOL         0.0424
      7 H4          1.2430    0.9310   -0.8700 H         1 MOL         0.0424
      8 H5          1.2620    0.9050    0.8890 H         1 MOL         0.0424
      9 Ho1        -1.1290    0.8360    0.8100 Ho        1 MOL         0.3960
@<TRIPOS>BOND
     1    1    2 1
     2    1    9 1
     3    2    3 1
     4    2    4 1
     5    2    5 1
     6    3    6 1
     7    3    7 1
     8    3    8 1
```

**Comment by davidlmobley** [comment]
OK, I tested this out and it seems to work now, in that my systems build. From my perspective this can (and should be) merged. Should I merge? 

I'll open an issue for the OpenEye stuff you mentioned.

(Also, for the record - if we want to package something, such as this, into a new point release and release it so it's conda installable, how is that done? My group will need it soon, though probably not quite yet - I think there's still a bit of separate GROMACS functionality we need to implement.)

**Comment by kyleabeauchamp** [comment]
So the conda installation is basically as simple as preparing a pull request on the omnia conda-recipes github.  For example, this pull request: https://github.com/omnia-md/conda-recipes/pull/184

**Pull request merged**
