### PR TITLE
Generalize AMBER mixture functionality to be able to handle non-GAFF water

### PR DESCRIPTION
**Pull request by davidlmobley**
This implements #134 for TIP3P and SPC/E water models by adding an optional argument, `water_model`, to `amber.build_mixture_prmtop`. The current default behavior is to use the TIP3P water model if nothing is specified, but flexible GAFF water will be used (the old behavior) if `water_model = None`. 

For three-point water models, no modification is necessary to the `openmoltools.packmol.pack_box` functionality, but for N-point water models (N != 3) substantially more modifications will be needed since the current framework is built around building boxes from .mol2 files, which will not (I don't think) be possible for non-three-point waters. I plan to create a separate issue for this.

On a tangential issue, this PR also updates `tleap` scripts to use the amber99SB force field under oldff, its new location in current AMBER distributions.

@kyleabeauchamp - note that I AM proposing to change the default behavior here so the default water is TIP3P rather than flexible GAFF water.

@gduarter - here's the code you were after. Please test and update. From the standpoint of building mixtures, your protocol should be exactly the same as before but now if you specify water, you should get TIP3P water rather than something else.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
OK, it looks like this builds upon #138,  so I might wait to review this until after the other is merged.  Otherwise it's a lot for me to digest.

**Comment by davidlmobley** [comment]
@kyleabeauchamp - yeah, sorry about that. No rush. I just put a request on ParmEd to get a new conda version with a recent bug fixed so that I can merge #138. Otherwise if I merge it, anyone who installs the new `openmoltools` will need to install ParmEd NOT from conda for GROMACS output to be correct.

**Comment by davidlmobley** [comment]
I'm still suffering from GitHub/git ignorance: Now that I've merged #138, which I built this on top of - what's the easiest way for me to update this PR to only reflect the NEW changes here? (i.e. a number of the changes here are now already in the main branch).

**Comment by kyleabeauchamp** [comment]
Fetch upstream then git merge upstream/master
Then commit and push.  Github should have a guide on this somewhere

**Comment by davidlmobley** [comment]
Done. Didn't realize that would resolve the present problem, but in hindsight it should be obvious. Thanks. :+1:

**Comment by jchodera** [comment]
> For three-point water models, no modification is necessary to the openmoltools.packmol.pack_box functionality, but for N-point water models (N != 3) substantially more modifications will be needed since the current framework is built around building boxes from .mol2 files, which will not (I don't think) be possible for non-three-point waters. I plan to create a separate issue for this.

Note that `simtk.openmm.app.Modeller` offers a method [`addExtraParticles`](http://docs.openmm.org/6.2.0/api-python/classsimtk_1_1openmm_1_1app_1_1modeller_1_1Modeller.html#ad59ef5b703f4dd7511858aa5d0be359d) to add any missing extra sites for multipoint waters defined with OpenMM `ffxml` files.  I'm not sure if it is feasible to utilize this in the pipeline or not.

Another possibility might be to try to split out or expand the functionality of `Modeller` as part of our discussion of how to make `Topology` objects more independently useful.

**Comment by davidlmobley** [comment]
Ah, now that sounds tremendously useful. Then we could just deal with
swapping the water model at the end of the topology/coordinate construction
process rather than in tleap, which will simplify a lot (I think).

BUT, there's that issue of `ffxml` though, maybe? Particularly, what if I
want to use `addExtraParticles` but end up in AMBER/GROMACS/other format?
I'm a little unclear on whether the fact that this involves ``ffxml` means
we'd be tied to OpenMM or whether we can still easily use ParmEd to get to
any other format ParmEd supports?

And yes, expanding (and potentially splitting out) the `Modeller`
functionality sounds good. Though I do wish it didn't have the same name as
UCSF Modeller, since we also use that sometimes.

On Fri, Jul 3, 2015 at 10:07 AM, John Chodera <notifications@github.com>
wrote:

> For three-point water models, no modification is necessary to the
> openmoltools.packmol.pack_box functionality, but for N-point water models
> (N != 3) substantially more modifications will be needed since the current
> framework is built around building boxes from .mol2 files, which will not
> (I don't think) be possible for non-three-point waters. I plan to create a
> separate issue for this.
>
> Note that simtk.openmm.app.Modeller offers a method addExtraParticles
> <http://docs.openmm.org/6.2.0/api-python/classsimtk_1_1openmm_1_1app_1_1modeller_1_1Modeller.html#ad59ef5b703f4dd7511858aa5d0be359d>
> to add any missing extra sites for multipoint waters defined with OpenMM
> ffxml files. I'm not sure if it is feasible to utilize this in the
> pipeline or not.
>
> Another possibility might be to try to split out or expand the
> functionality of Modeller as part of our discussion of how to make
> Topology objects more independently useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/pull/142#issuecomment-118393306>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
I think this is ready to merge once the Travis-CI test passes and someone reviews. I just restarted the test - it had run into the issue with the OpenEye license, apparently.

**Comment by davidlmobley** [comment]
@jchodera - it looks like there is some sort of an issue with the OpenEye keys still so that Travis-CI won't test this.

**Comment by davidlmobley** [comment]
@jchodera - I'm STILL having the same issue with the OpenEye stuff on this PR, even after your fix from earlier today:

```33.54s$ source devtools/ci/install.sh
--2015-07-08 20:04:09--  http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 107.20.205.196, 75.101.148.13, 54.83.3.29, ...
Connecting to repo.continuum.io (repo.continuum.io)|107.20.205.196|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23767393 (23M) [application/octet-stream]
Saving to: `Miniconda-latest-Linux-x86_64.sh'
100%[======================================>] 23,767,393  85.1M/s   in 0.3s    
2015-07-08 20:04:10 (85.1 MB/s) - `Miniconda-latest-Linux-x86_64.sh' saved [23767393/23767393]
PREFIX=/home/travis/miniconda
installing: python-2.7.9-3 ...
installing: conda-env-2.1.4-py27_0 ...
installing: openssl-1.0.1k-1 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_0 ...
installing: readline-6.2-2 ...
installing: requests-2.6.0-py27_0 ...
installing: sqlite-3.8.4.1-1 ...
installing: system-5.8-2 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.4-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.10.1-py27_0 ...
Python 2.7.9 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Get:1 http://downloads-distro.mongodb.org dist Release.gpg [490 B]
Get:2 http://downloads-distro.mongodb.org dist Release [2,040 B]
Get:3 http://security.ubuntu.com precise-security Release.gpg [198 B]
Hit http://us.archive.ubuntu.com precise Release.gpg
Get:4 http://us.archive.ubuntu.com precise-updates Release.gpg [198 B]
Get:5 http://us.archive.ubuntu.com precise-backports Release.gpg [198 B]
Get:6 http://downloads-distro.mongodb.org dist/10gen amd64 Packages [29.1 kB]
Get:7 http://security.ubuntu.com precise-security Release [54.3 kB]
Hit http://us.archive.ubuntu.com precise Release
Get:8 http://us.archive.ubuntu.com precise-updates Release [196 kB]
Get:9 http://downloads-distro.mongodb.org dist/10gen i386 Packages [28.8 kB]
Ign http://downloads-distro.mongodb.org dist/10gen TranslationIndex
Get:10 http://apt.postgresql.org precise-pgdg Release.gpg [819 B]
Ign http://downloads-distro.mongodb.org dist/10gen Translation-en_US
Get:11 http://security.ubuntu.com precise-security/main Sources [131 kB]
Ign http://downloads-distro.mongodb.org dist/10gen Translation-en
Get:12 http://apt.postgresql.org precise-pgdg Release [36.5 kB]
Get:13 http://us.archive.ubuntu.com precise-backports Release [54.3 kB]
Hit http://us.archive.ubuntu.com precise/main Sources
Hit http://us.archive.ubuntu.com precise/restricted Sources
Hit http://us.archive.ubuntu.com precise/universe Sources
Hit http://us.archive.ubuntu.com precise/multiverse Sources
Hit http://us.archive.ubuntu.com precise/main amd64 Packages
Hit http://us.archive.ubuntu.com precise/restricted amd64 Packages
Hit http://us.archive.ubuntu.com precise/universe amd64 Packages
Hit http://us.archive.ubuntu.com precise/multiverse amd64 Packages
Hit http://us.archive.ubuntu.com precise/main i386 Packages
Hit http://us.archive.ubuntu.com precise/restricted i386 Packages
Get:14 http://security.ubuntu.com precise-security/restricted Sources [3,759 B]
Hit http://us.archive.ubuntu.com precise/universe i386 Packages
Hit http://us.archive.ubuntu.com precise/multiverse i386 Packages
Hit http://us.archive.ubuntu.com precise/main TranslationIndex
Hit http://us.archive.ubuntu.com precise/multiverse TranslationIndex
Hit http://us.archive.ubuntu.com precise/restricted TranslationIndex
Get:15 http://security.ubuntu.com precise-security/universe Sources [43.8 kB]
Get:16 http://security.ubuntu.com precise-security/multiverse Sources [2,204 B]
Hit http://ppa.launchpad.net precise Release.gpg
Hit http://ppa.launchpad.net precise Release.gpg
Get:17 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:18 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:19 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:20 http://ppa.launchpad.net precise Release.gpg [316 B]
Hit http://us.archive.ubuntu.com precise/universe TranslationIndex
Get:21 http://security.ubuntu.com precise-security/main amd64 Packages [529 kB]
Get:22 http://us.archive.ubuntu.com precise-updates/main Sources [490 kB]
Get:23 http://apt.postgresql.org precise-pgdg/main amd64 Packages [53.9 kB]
Hit http://ppa.launchpad.net precise Release
Get:24 http://us.archive.ubuntu.com precise-updates/restricted Sources [7,981 B]
Get:25 http://us.archive.ubuntu.com precise-updates/universe Sources [122 kB]
Get:26 http://us.archive.ubuntu.com precise-updates/multiverse Sources [9,720 B]
Get:27 http://us.archive.ubuntu.com precise-updates/main amd64 Packages [915 kB]
Get:28 http://security.ubuntu.com precise-security/restricted amd64 Packages [8,943 B]
Get:29 http://security.ubuntu.com precise-security/universe amd64 Packages [123 kB]
Get:30 http://apt.postgresql.org precise-pgdg/main i386 Packages [54.0 kB]
Get:31 http://security.ubuntu.com precise-security/multiverse amd64 Packages [2,679 B]
Get:32 http://security.ubuntu.com precise-security/main i386 Packages [573 kB]
Ign http://apt.postgresql.org precise-pgdg/main TranslationIndex
Get:33 http://us.archive.ubuntu.com precise-updates/restricted amd64 Packages [13.6 kB]
Get:34 http://us.archive.ubuntu.com precise-updates/universe amd64 Packages [268 kB]
Get:35 http://security.ubuntu.com precise-security/restricted i386 Packages [8,939 B]
Get:36 http://security.ubuntu.com precise-security/universe i386 Packages [131 kB]
Get:37 http://us.archive.ubuntu.com precise-updates/multiverse amd64 Packages [16.5 kB]
Get:38 http://us.archive.ubuntu.com precise-updates/main i386 Packages [967 kB]
Get:39 http://security.ubuntu.com precise-security/multiverse i386 Packages [2,859 B]
Get:40 http://security.ubuntu.com precise-security/main TranslationIndex [208 B]
Get:41 http://security.ubuntu.com precise-security/multiverse TranslationIndex [199 B]
Get:42 http://security.ubuntu.com precise-security/restricted TranslationIndex [202 B]
Get:43 http://security.ubuntu.com precise-security/universe TranslationIndex [205 B]
Hit http://ppa.launchpad.net precise Release
Get:44 http://ppa.launchpad.net precise Release [12.9 kB]
Get:45 http://security.ubuntu.com precise-security/main Translation-en [232 kB]
Get:46 http://security.ubuntu.com precise-security/multiverse Translation-en [1,408 B]
Hit http://security.ubuntu.com precise-security/restricted Translation-en
Get:47 http://us.archive.ubuntu.com precise-updates/restricted i386 Packages [13.6 kB]
Get:48 http://us.archive.ubuntu.com precise-updates/universe i386 Packages [277 kB]
Get:49 http://us.archive.ubuntu.com precise-updates/multiverse i386 Packages [16.7 kB]
Get:50 http://us.archive.ubuntu.com precise-updates/main TranslationIndex [10.6 kB]
Get:51 http://us.archive.ubuntu.com precise-updates/multiverse TranslationIndex [7,613 B]
Get:52 http://us.archive.ubuntu.com precise-updates/restricted TranslationIndex [7,297 B]
Get:53 http://us.archive.ubuntu.com precise-updates/universe TranslationIndex [8,333 B]
Get:54 http://us.archive.ubuntu.com precise-backports/main Sources [5,411 B]
Get:55 http://us.archive.ubuntu.com precise-backports/restricted Sources [28 B]
Get:56 http://security.ubuntu.com precise-security/universe Translation-en [77.5 kB]
Get:57 http://us.archive.ubuntu.com precise-backports/universe Sources [42.8 kB]
Get:58 http://us.archive.ubuntu.com precise-backports/multiverse Sources [5,750 B]
Get:59 http://us.archive.ubuntu.com precise-backports/main amd64 Packages [5,491 B]
Get:60 http://us.archive.ubuntu.com precise-backports/restricted amd64 Packages [28 B]
Get:61 http://us.archive.ubuntu.com precise-backports/universe amd64 Packages [44.2 kB]
Get:62 http://us.archive.ubuntu.com precise-backports/multiverse amd64 Packages [5,419 B]
Get:63 http://us.archive.ubuntu.com precise-backports/main i386 Packages [5,484 B]
Get:64 http://us.archive.ubuntu.com precise-backports/restricted i386 Packages [28 B]
Get:65 http://us.archive.ubuntu.com precise-backports/universe i386 Packages [44.0 kB]
Get:66 http://us.archive.ubuntu.com precise-backports/multiverse i386 Packages [5,413 B]
Get:67 http://us.archive.ubuntu.com precise-backports/main TranslationIndex [202 B]
Get:68 http://us.archive.ubuntu.com precise-backports/multiverse TranslationIndex [202 B]
Get:69 http://us.archive.ubuntu.com precise-backports/restricted TranslationIndex [193 B]
Get:70 http://us.archive.ubuntu.com precise-backports/universe TranslationIndex [205 B]
Hit http://us.archive.ubuntu.com precise/main Translation-en
Hit http://us.archive.ubuntu.com precise/multiverse Translation-en
Hit http://us.archive.ubuntu.com precise/restricted Translation-en
Hit http://us.archive.ubuntu.com precise/universe Translation-en
Get:71 http://ppa.launchpad.net precise Release [12.9 kB]
Get:72 http://us.archive.ubuntu.com precise-updates/main Translation-en [399 kB]
Get:73 http://ppa.launchpad.net precise Release [12.9 kB]
Get:74 http://us.archive.ubuntu.com precise-updates/multiverse Translation-en [9,603 B]
Hit http://us.archive.ubuntu.com precise-updates/restricted Translation-en
Get:75 http://us.archive.ubuntu.com precise-updates/universe Translation-en [160 kB]
Hit http://us.archive.ubuntu.com precise-backports/main Translation-en
Hit http://us.archive.ubuntu.com precise-backports/multiverse Translation-en
Hit http://us.archive.ubuntu.com precise-backports/restricted Translation-en
Get:76 http://us.archive.ubuntu.com precise-backports/universe Translation-en [35.0 kB]
Get:77 http://ppa.launchpad.net precise Release [13.0 kB]
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Hit http://ppa.launchpad.net precise/main TranslationIndex
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Hit http://ppa.launchpad.net precise/main TranslationIndex
Get:78 http://ppa.launchpad.net precise/main amd64 Packages [691 B]
Get:79 http://ppa.launchpad.net precise/main i386 Packages [690 B]
Get:80 http://ppa.launchpad.net precise/main TranslationIndex [196 B]
Get:81 http://ppa.launchpad.net precise/main amd64 Packages [1,398 B]
Get:82 http://ppa.launchpad.net precise/main i386 Packages [943 B]
Ign http://apt.postgresql.org precise-pgdg/main Translation-en_US
Get:83 http://ppa.launchpad.net precise/main TranslationIndex [199 B]
Hit http://ppa.launchpad.net precise/main Translation-en
Get:84 http://ppa.launchpad.net precise/main amd64 Packages [29.9 kB]
Ign http://apt.postgresql.org precise-pgdg/main Translation-en
Get:85 http://ppa.launchpad.net precise/main i386 Packages [29.8 kB]
Get:86 http://ppa.launchpad.net precise/main TranslationIndex [202 B]
Get:87 http://ppa.launchpad.net precise/main amd64 Packages [3,363 B]
Get:88 http://ppa.launchpad.net precise/main i386 Packages [3,363 B]
Get:89 http://ppa.launchpad.net precise/main TranslationIndex [199 B]
Hit http://ppa.launchpad.net precise/main Translation-en
Get:90 http://ppa.launchpad.net precise/main Translation-en [464 B]
Get:91 http://ppa.launchpad.net precise/main Translation-en [735 B]
Get:92 http://ppa.launchpad.net precise/main Translation-en [15.7 kB]
Get:93 http://ppa.launchpad.net precise/main Translation-en [1,556 B]
Fetched 6,445 kB in 3s (1,790 kB/s)
Reading package lists... Done
Preconfiguring packages ...
(Reading database ... 76763 files and directories currently installed.)
Preparing to replace libc6-dev 2.15-0ubuntu10 (using .../libc6-dev_2.15-0ubuntu10.12_amd64.deb) ...
Unpacking replacement libc6-dev ...
Preparing to replace libc-dev-bin 2.15-0ubuntu10 (using .../libc-dev-bin_2.15-0ubuntu10.12_amd64.deb) ...
Unpacking replacement libc-dev-bin ...
Preparing to replace libc-bin 2.15-0ubuntu10 (using .../libc-bin_2.15-0ubuntu10.12_amd64.deb) ...
Unpacking replacement libc-bin ...
Processing triggers for man-db ...
Setting up libc-bin (2.15-0ubuntu10.12) ...
(Reading database ... 76762 files and directories currently installed.)
Preparing to replace libc6 2.15-0ubuntu10 (using .../libc6_2.15-0ubuntu10.12_amd64.deb) ...
Unpacking replacement libc6 ...
Setting up libc6 (2.15-0ubuntu10.12) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Selecting previously unselected package libc6-i386.
(Reading database ... 76762 files and directories currently installed.)
Unpacking libc6-i386 (from .../libc6-i386_2.15-0ubuntu10.12_amd64.deb) ...
Selecting previously unselected package libc6-dev-i386.
Unpacking libc6-dev-i386 (from .../libc6-dev-i386_2.15-0ubuntu10.12_amd64.deb) ...
Selecting previously unselected package lib32gcc1.
Unpacking lib32gcc1 (from .../lib32gcc1_1%3a4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package lib32gomp1.
Unpacking lib32gomp1 (from .../lib32gomp1_4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package lib32quadmath0.
Unpacking lib32quadmath0 (from .../lib32quadmath0_4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package gcc-4.6-multilib.
Unpacking gcc-4.6-multilib (from .../gcc-4.6-multilib_4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package gcc-multilib.
Unpacking gcc-multilib (from .../gcc-multilib_4%3a4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package csh.
Unpacking csh (from .../csh_20110502-2ubuntu1_amd64.deb) ...
Selecting previously unselected package lib32stdc++6.
Unpacking lib32stdc++6 (from .../lib32stdc++6_4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package g++-4.6-multilib.
Unpacking g++-4.6-multilib (from .../g++-4.6-multilib_4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package g++-multilib.
Unpacking g++-multilib (from .../g++-multilib_4%3a4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package gfortran-4.6.
Unpacking gfortran-4.6 (from .../gfortran-4.6_4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package gfortran.
Unpacking gfortran (from .../gfortran_4%3a4.6.3-1ubuntu5_amd64.deb) ...
Selecting previously unselected package libopenbabel4.
Unpacking libopenbabel4 (from .../libopenbabel4_2.3.0+dfsg-3ubuntu3_amd64.deb) ...
Selecting previously unselected package openbabel.
Unpacking openbabel (from .../openbabel_2.3.0+dfsg-3ubuntu3_amd64.deb) ...
Processing triggers for ccache ...
Updating symlinks in /usr/lib/ccache ...
Processing triggers for man-db ...
Setting up libc-dev-bin (2.15-0ubuntu10.12) ...
Setting up libc6-dev (2.15-0ubuntu10.12) ...
Setting up libc6-i386 (2.15-0ubuntu10.12) ...
Setting up libc6-dev-i386 (2.15-0ubuntu10.12) ...
Setting up lib32gcc1 (1:4.6.3-1ubuntu5) ...
Setting up lib32gomp1 (4.6.3-1ubuntu5) ...
Setting up lib32quadmath0 (4.6.3-1ubuntu5) ...
Setting up gcc-4.6-multilib (4.6.3-1ubuntu5) ...
Setting up gcc-multilib (4:4.6.3-1ubuntu5) ...
Setting up csh (20110502-2ubuntu1) ...
update-alternatives: using /bin/bsd-csh to provide /bin/csh (csh) in auto mode.
Setting up lib32stdc++6 (4.6.3-1ubuntu5) ...
Setting up g++-4.6-multilib (4.6.3-1ubuntu5) ...
Setting up g++-multilib (4:4.6.3-1ubuntu5) ...
Setting up gfortran-4.6 (4.6.3-1ubuntu5) ...
Setting up gfortran (4:4.6.3-1ubuntu5) ...
update-alternatives: using /usr/bin/gfortran to provide /usr/bin/f95 (f95) in auto mode.
Setting up libopenbabel4 (2.3.0+dfsg-3ubuntu3) ...
Setting up openbabel (2.3.0+dfsg-3ubuntu3) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/travis/miniconda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    yaml-0.1.6                 |                0         246 KB
    conda-env-2.2.3            |           py27_0          21 KB
    python-2.7.10              |                0        13.5 MB
    pyyaml-3.11                |           py27_1         295 KB
    requests-2.7.0             |           py27_0         594 KB
    setuptools-18.0.1          |           py27_0         341 KB
    conda-3.14.1               |           py27_0         169 KB
    pip-7.1.0                  |           py27_0         1.4 MB
    ------------------------------------------------------------
                                           Total:        16.4 MB
The following NEW packages will be INSTALLED:
    pip:        7.1.0-py27_0 
    setuptools: 18.0.1-py27_0
The following packages will be UPDATED:
    conda:      3.10.1-py27_0 --> 3.14.1-py27_0
    conda-env:  2.1.4-py27_0  --> 2.2.3-py27_0 
    python:     2.7.9-3       --> 2.7.10-0     
    pyyaml:     3.11-py27_0   --> 3.11-py27_1  
    requests:   2.6.0-py27_0  --> 2.7.0-py27_0 
    yaml:       0.1.4-0       --> 0.1.6-0      
Fetching packages ...
yaml-0.1.6-0.t 100% |################################| Time: 0:00:00  14.01 MB/s
conda-env-2.2. 100% |################################| Time: 0:00:00  12.65 MB/s
python-2.7.10- 100% |################################| Time: 0:00:00  35.39 MB/s
pyyaml-3.11-py 100% |################################| Time: 0:00:00  14.33 MB/s
requests-2.7.0 100% |################################| Time: 0:00:00  16.46 MB/s
setuptools-18. 100% |################################| Time: 0:00:00  15.42 MB/s
conda-3.14.1-p 100% |################################| Time: 0:00:00  12.79 MB/s
pip-7.1.0-py27 100% |################################| Time: 0:00:00  21.27 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
Error: could not find environment: 2.7
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/travis/miniconda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    patchelf-0.6               |                0         179 KB
    markupsafe-0.23            |           py27_0          30 KB
    jinja2-2.7.3               |           py27_1         308 KB
    conda-build-1.14.1         |           py27_0         194 KB
    ------------------------------------------------------------
                                           Total:         710 KB
The following NEW packages will be INSTALLED:
    conda-build: 1.14.1-py27_0
    jinja2:      2.7.3-py27_1 
    markupsafe:  0.23-py27_0  
    patchelf:    0.6-0        
Fetching packages ...
patchelf-0.6-0 100% |################################| Time: 0:00:00  13.93 MB/s
markupsafe-0.2 100% |################################| Time: 0:00:00  10.43 MB/s
jinja2-2.7.3-p 100% |################################| Time: 0:00:00  11.74 MB/s
conda-build-1. 100% |################################| Time: 0:00:00  12.80 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
before_install.2
0.01s$ export PYTHONUNBUFFERED=true
0.01s$ openssl aes-256-cbc -K $encrypted_dc22cc99e02f_key -iv $encrypted_dc22cc99e02f_iv -in oe_license.txt.enc -out oe_license.txt -d
iv undefined
The command "openssl aes-256-cbc -K $encrypted_dc22cc99e02f_key -iv $encrypted_dc22cc99e02f_iv -in oe_license.txt.enc -out oe_license.txt -d" failed and exited with 1 during .
```

**Comment by kyleabeauchamp** [comment]
Could something be hardcoded to prevent this from working on mobleys fork?

**Comment by davidlmobley** [comment]
Ah, @kyleabeauchamp - so that's the problem? It's trying to run the OpenEye stuff on my fork rather than here, and choking?

**Comment by kyleabeauchamp** [comment]
No idea, just throwing ideas out

**Comment by jchodera** [comment]
Oh, good point.  The files cannot be decrypted in pull requests, since this would be a security risk in allowing you to modify `.travis.yml` to print out the contents of the decrypted file and just file a PR to build it.  Hm.  

I can have travis not try to decrypt the file in PRs, but that does limit the utility somewhat.  But that's better than the current situation.  Let me try that.

**Comment by jchodera** [comment]
OK, thanks to PR #145, the OpenEye license will only be decrypted (and OE toolkits only available) in commits to the repo itself.

**Comment by jchodera** [comment]
Rerunning travis for this PR...

**Comment by davidlmobley** [comment]
I would like to merge this, but Travis-CI is still running into the same issue it seems. I just restarted it one more time just to double-check.

**Comment by jchodera** [comment]
Do you have to do a merge from `upstream/master`?

**Comment by jchodera** [comment]
If it doesn't work after that, go ahead and merge and I'll see if I can fix things in a separate PR.

**Comment by davidlmobley** [comment]
Ahh, good point, let me try that.

**Comment by jchodera** [comment]
Woohoo!

**Pull request merged**
