### PR TITLE
Add option to use alternate leaprc to run_tleap

### PR DESCRIPTION
**Pull request by davidlmobley**
I'd like to set up some small molecules with gaff2, not just gaff, so I added the option to `run_tleap` to optionally specify an alternate leaprc file.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Tests are failing, but seems not to have to do with this PR. Likely something has changed WRT to Travis since the last change was made to openmoltools. Will have to investigate later.

**Comment by jchodera** [comment]
I think I know what it is. Will fix in the morning.

**Comment by davidlmobley** [comment]
@jchodera - you have some insight and possibly a fix? Thanks.

**Comment by jchodera** [comment]
On it.

**Comment by jchodera** [comment]
Fixed.

**Pull request merged**
