### PR TITLE
Fix bytes decoding for python 3 compatibility

### PR DESCRIPTION
**Pull request by andrrizzi**
Bug fix before release.

### CODE REVIEW

**Comment by andrrizzi** [comment]
Weird, we didn't get those test errors before. The only difference with the previous built is that for some reason now we are installing ``libgfortran-3.0`` instead of ``libgfortran-1.0``.

**Comment by andrrizzi** [comment]
Yep, it's almost surely [that](https://travis-ci.org/choderalab/openmoltools/jobs/113539893#L1420).

**Comment by andrrizzi** [comment]
So I think the problem is that ``scipy`` installs the latest version ``libgfortran-3.0`` (which was uploaded [15 hours ago](https://anaconda.org/anaconda/libgfortran/files)) but both [``packmol``](https://travis-ci.org/choderalab/openmoltools/jobs/113539893#L1178) and [``sqm``](https://travis-ci.org/choderalab/openmoltools/jobs/113539893#L1420) require ``GFORTRAN_1.4``.

Now that gfortran is conda-installable, we could think of updating the recipes of ``packmol`` and ``ambermini`` to install version ``1.0``.

**Comment by jchodera** [comment]
Good catch!  Tagging @swails regarding `ambermini`.

I'll fix `packmol`.

**Comment by jchodera** [comment]
`packmol` only uses `gcc` and `libgcc`:
https://github.com/omnia-md/conda-recipes/blob/master/packmol/meta.yaml

Any idea why it ended up with a `GFORTRAN_1.4` requirement?

**Comment by jchodera** [comment]
Oh, I see---you're suggesting we add `libgfortran ==1.0` to the requirements for `packmol` and `ambermini`.  If we do, won't this conflict with the `scipy` receipe that requires `libgfortran ==3.0`?

**Comment by andrrizzi** [comment]
I think both ``ambermini`` and ``packmol`` didn't install ``gfortran`` but were expecting it to be already installed (at least this is what their ``README.md`` says).

> If we do, won't this conflict with the ``scipy`` receipe that requires ``libgfortran == 3.0``?

Right, could be. I'm actually not sure whether ``scipy`` needs version ``3.0`` or if there's a build compatible with ``gfortran 1.0``. I guess we can just check if ``conda`` complains when it builds.

**Comment by jchodera** [comment]
I'm still confused by the `libgfortran` requirement for `packmol`.  `packmol` gets compiled by the `gfortran` installed with the `gcc` package, which is currently 4.8.5:
https://anaconda.org/anaconda/gcc/files

I'm not sure what `libgfortran` 1.0 or 3.0 has to do with this.  Shouldn't we be requiring the corresponding `libgcc` if anything?
https://anaconda.org/anaconda/libgcc/files

**Comment by jchodera** [comment]
I've merged what is hopefully a fix in https://github.com/omnia-md/conda-recipes/issues/459

**Comment by andrrizzi** [comment]
> ``packmol`` gets compiled by the ``gfortran`` installed with the ``gcc`` package

My best guess is that there are compatibility issues when you install ``libgfortran-3.0`` on top of ``libgcc``. Probably they do get compiled with the version in the ``gcc`` package (which is 1.4) but when it is dynamically link to the ``.so`` library it finds only the 3.0 version. The errors happens at runtime, not during the build.

> I've merged what is hopefully a fix

Great, thanks! I'll try to trigger the build again.

**Comment by jchodera** [comment]
You will need to wait for the conda packages to build and upload before
retriggering the build.

**Comment by andrrizzi** [comment]
Oh, right! I'll try again later then.

**Comment by swails** [comment]
I'm not sure the best thing to do here, as I'm struggling with the same issue for the pysander conda package.  I'd be interested to hear whatever you get figured out.

**Comment by jchodera** [comment]
Packmol has been rebuilt in a way that fixes the segfaults and `GFORTRAN` issues.

**Comment by jchodera** [comment]
@andrrizzi: Would be great if you made changes via a branch in the `choderalab/openmoltools` next time, since the openeye tests will only work in branches of the main repo.

Merging this anyway.

**Comment by andrrizzi** [comment]
> openeye tests will only work in branches of the main repo

Ok, thanks! I'll do it for the release and when I modify the `openeye` parts.

**Pull request merged**
