### PR TITLE
If sigma and epsilon both = 0, sigma = 1

### PR DESCRIPTION
**Pull request by juliebehr**

### CODE REVIEW

**Comment by davidlmobley** [comment]
@juliebehr - this PR is still hanging out here un-merged waiting for an answer to my question. Can you clarify? Thanks.

**Comment by rmcgibbo** [comment]
Some discussion of this issue in https://github.com/pandegroup/openmm/issues/979, https://github.com/pandegroup/openmm/issues/732

**Comment by rafwiewiora** [comment]
See also my comment here: https://github.com/pandegroup/openmm/issues/1054#issuecomment-131999093

and PR: https://github.com/pandegroup/openmm/pull/1133

I don't know if you guys would be using the FFs here that would cause this problem, probably, so note that the code changes you've made here are not sufficient to solve this. There might be hydrogens in Amber FFs that have vdW parameters listed, but listed as both epsilon = 0, sigma = 0 (the one I found was class `HO`, see first link). Hence you need a further if clause to fix this, as in the PR in second link.

Hope this helps!

**Comment by rafwiewiora** [comment]
Also just a thought coz guys here were talking about it: I don't think OpenMM code has division by sigma anywhere, this was only a problem for custom expression with /sigma divisions for `CustomNonbondedForce`. 

Also note that we're nearly done with the Amber --> ffxml conversion in ParmEd (https://github.com/ParmEd/ParmEd/issues/486) if you guys want to switch to using that.

**Comment by davidlmobley** [comment]
I'm not sure who, if anyone, here uses the ffxml stuff in openmoltools. My
group certainly doesn't. We should sort this out after John Chodera emerges
from grant mode.

On Wed, Jan 20, 2016 at 1:37 PM, Rafal Wiewiora <notifications@github.com>
wrote:

> Also just a thought coz guys here were talking about it: I don't think
> OpenMM code has division by sigma anywhere, this was only a problem for
> custom expression with /sigma divisions for CustomNonbondedForce.
>
> Also note that we're nearly done with the Amber --> ffxml conversion in
> ParmEd (ParmEd/ParmEd#486 <https://github.com/ParmEd/ParmEd/issues/486>)
> if you guys want to switch to using that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/pull/156#issuecomment-173367700>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by juliebehr** [comment]
Sorry for the delay, I thought this had been addressed in October -- I was under the impression it was a divide by 0 issue, as has been suggested, but I made this change and PR per request from John.  Thank you @rmcgibbo and @rafwiewiora for the insight!

**Comment by davidlmobley** [comment]
I'm OK with merging, but it sounds like (from the comments) you still need
one more if statement to finish addressing the divide-by-zero issue, so if
indeed that's the case I'd prefer to have that addressed before merging.

(Submitting a PR is not quite the end of the road, in that someone has to
review the PR and merge it once it passes tests, and if - as in this case -
it's not quite completely explained and nobody bothers (cares?) to hit the
"merge" button, it can sit there for a long time without being merged.)

On Wed, Jan 20, 2016 at 2:19 PM, juliebehr <notifications@github.com> wrote:

> Sorry for the delay, I thought this had been addressed in October -- I was
> under the impression it was a divide by 0 issue, as has been suggested, but
> I made this change and PR per request from John. Thank you @rmcgibbo
> <https://github.com/rmcgibbo> and @rafwiewiora
> <https://github.com/rafwiewiora> for the insight!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/pull/156#issuecomment-173380143>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by bas-rustenburg** [comment]
>I'm not sure who, if anyone, here uses the ffxml stuff in openmoltools. 
I use it, but I'm not intimately familiar with the particular issue. Maybe it would be less wrong to set sigma to machine epsilon? (Not to be confused with the epsilon in the potential). I think I've seen @jchodera apply this somewhere in the constant-pH code. 

Tagging @jchodera, since he might have more knowledge on this.

**Pull request merged**
