### PR TITLE
Switch to new OpenEye BETA toolkit.

### PR DESCRIPTION
**Pull request by jchodera**
This switches travis to the new OpenEye ` 2015.Oct` BETA toolkit and updates `binstar` to `anaconda`.

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
@jchodera This switches everything to the beta, correct? While I'm usually all for new features and beta testing, my fear is we'd make debugging complicated. We might not be able to spot if we broke something, or there is something broken on the OpenEye side.  Perhaps we could/should set up a travis build matrix with different OpenEye versions?

**Comment by davidlmobley** [comment]
I like Bas's suggestion here. Otherwise, a new commit may raise red flags
simply because OpenEye broke something, and we may spend a good deal of
time trying to find our mistake. Seems like it would be nice to be testing
BOTH OE versions since that would immediately tell us the problem is with
the beta.

Thanks.

On Fri, Sep 11, 2015 at 9:28 AM, Bas Rustenburg <notifications@github.com>
wrote:

> @jchodera <https://github.com/jchodera> This switches everything to the
> beta, correct? While I'm usually all for new features and beta testing, my
> fear is we'd make debugging complicated. We might not be able to spot if we
> broke something, or there is something broken on the OpenEye side. Perhaps
> we could/should set up a travis build matrix with different OpenEye
> versions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/pull/151#issuecomment-139591766>
> .
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by bas-rustenburg** [comment]
Thinking one step beyond that, not everyone can use the latest version everywhere, for reasons of licensing or compatibility with other tools. Since it's not a simple matter of typing `conda update openeye` to get the latest version either, we might want to explicitly track the OpenEye versions that work, and that we choose to support.

**Comment by bas-rustenburg** [comment]
Perhaps we can discuss that further on the issue tracker. This PR looks okay, with the exception that it's not running openeye tests. Not sure if that is expected, but if we switch versions, it really should be testing those: https://travis-ci.org/choderalab/openmoltools/jobs/79866936#L1635

**Comment by jchodera** [comment]
The idea here is that we should be testing against the new OpenEye tools to make sure that an OpenEye toolkit release won't break everything when users upgrade.  But I like the suggestion that we should test against both production and beta versions.

OpenEye tests should definitely be running on travis---I'll try to figure out why they aren't.

**Comment by jchodera** [comment]
We were testing twice, for some reason---once in the conda dev recipe (which couldn't run OpenEye tools) and once again after that.  I've cut this down to one test using the OpenEye tools.

**Comment by jchodera** [comment]
We are also hopefully now testing with both production and beta openeye tools.

**Comment by jchodera** [comment]
I'm not sure why the OpenEye tests are still being skipped...

**Comment by jchodera** [comment]
The OpenEye tests *cannot* be run in pull requests because that would potentially expose encrypted file information.  I'll merge this since I think things are working with both old/new OpenEye tests now.

**Pull request merged**
