### PR TITLE
Add method to build peptide

### PR DESCRIPTION
**Pull request by pgrinaway**
Added a method to build a peptide with tleap, and a simple test.

### CODE REVIEW

**Comment by pgrinaway** [comment]
These need to be minimized btw--tleap doesn't exactly generate brilliant geometry.

**Comment by pgrinaway** [comment]
oops, found a little mistake. one sec.

**Comment by pgrinaway** [comment]
This can be merged.

**Comment by jchodera** [comment]
Thanks!

**Comment by pgrinaway** [comment]
np!

**Pull request merged**
