### PR TITLE
Add normalize option to template generators

### PR DESCRIPTION
**Pull request by bas-rustenburg**
Why:

By default, the template/ForceField generators normalize the molecule in terms of atom and residue name. There are use cases where it is preferable to maintain the input names.
I added an option to prevent normalization. The default produces the
current behavior.

This change addresses the need by:

* Adding new keyword argument 'normalize' to
  - `generateResidueTemplate`
  - `generateForceFieldFromMolecules`

* Passing this to the normalize flag of the `get_charges` command.

### CODE REVIEW

**Comment by jchodera** [comment]
Looks OK to me.

**Comment by bas-rustenburg** [comment]
The build seems to be failing, is that the http/https issue again? I can fix that in a separate PR.

**Comment by jchodera** [comment]
#238 merged and build restarted

**Comment by bas-rustenburg** [comment]
Merged the new master into the branch.

**Pull request merged**
