### PR TITLE
Update version tag for ongoing development (after 0.6.8 release)

### PR DESCRIPTION
**Pull request by davidlmobley**

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like tests are failing:
https://travis-ci.org/choderalab/openmoltools/jobs/67233407#L1072-L1086

**Comment by jchodera** [comment]
Is this because `parmed` hasn't been uploaded to binstar yet?

**Comment by davidlmobley** [comment]
No, it's actually because OpenMM 6.3 is not out and some ParmEd functionality requires it. Kyle and I thought this was OK while we wait for the release which I believe is supposed to be soon (as we discussed elsewhere on here). The alternative is to switch the conda recipes to install openmm-dev and switch back later. Thoughts?

**Comment by jchodera** [comment]
Why not just use `openmm-dev` for now?

**Comment by davidlmobley** [comment]
Fixed here. Not sure if this should also be changed for the omnia channel...?

**Comment by jchodera** [comment]
> Fixed here. Not sure if this should also be changed for the omnia channel...?

**Comment by jchodera** [comment]
> Fixed here. Not sure if this should also be changed for the omnia channel...?

You mean the conda recipe in the `omnia-md/conda-recipes` repo? 

Yes, if it requires OpenMM 6.3, we definitely need to switch that to `openmm-dev` for now.

I just found out that `openmm-dev` hasn't been updating recently---fixing that now.
https://github.com/pandegroup/openmm/issues/971

**Comment by davidlmobley** [comment]
Yes, that's what I meant. Will fix soon, or you can (since I can't merge).

On Wed, Jun 17, 2015 at 11:57 AM, John Chodera <notifications@github.com>
wrote:

> Fixed here. Not sure if this should also be changed for the omnia
> channel...?
>
> You mean the conda recipe in the omnia-md/conda-recipes repo?
>
> Yes, if it requires OpenMM 6.3, we definitely need to switch that to
> openmm-dev for now.
>
> I just found out that openmm-dev hasn't been updating recently---fixing
> that now.
> pandegroup/openmm#971 <https://github.com/pandegroup/openmm/issues/971>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/pull/126#issuecomment-112913735>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Pull request merged**
