### PR TITLE
[WIP] Addition of water solvation do_solvate function to utils.py.

### PR DESCRIPTION
**Pull request by gduarter**
Added do_solvate function. It is supposed to create water solvated molecule coordinate files and their topologies.

### CODE REVIEW

**Comment by davidlmobley** [comment]
@gduarter - I want to push out a new version of this and get this change in first, so I think I'll go ahead and see if I can address the issues I just raised. So have a look at them for your information, but I'll try and address them right now.

**Comment by gduarter** [comment]
Hi @davidlmobley

> Why 3.1f? Should be any float is supported, right?
1) yes, it accepts any floating number, but it is rounded off to that form. I thought a 100 nm-sided box wouldn't be very interesting (this might be my own bias here) but that can be easily changed in the code.

>What if I want to use amber99sb-ildn (my current preference)? (So I think this line should read os.path.join(FF, water_top)). Also, if you retain the new/old version stuff here, you'll need to add a conditional as this line only applies to the new version. In the old version, it would be JUST the water itp file without the FF prefix, i.e.: wateritp = water_top.
2) With regard to the amber forcefield, I can change that. That is actually a very good point.

> think you want, "water model .itp file to check for/be included in topology file", rather than what you currently have. An .itp file is not quite the same as a topology file. Probably also give an example in the doc string, such as "i.e. 'tip3p.itp'".
3) Whoops, doesn't the .itp files carried specific topologic information? I know it is not a topology file per se -- that would be the .top file it would be included -- but it carries important details. I'm sorry for my lack of nomenclature skills. I'll change that right away and next time I'll ask first before naming things.

> Have you tested this? I think it should be os.stat( gro_solv_filename ).st_size==0, not os.stat(gro_solv_filename) = 0.
4) Well, the code run yesterday. I might've made a mistake (and for some reason it still runs) but I'll check this issue right now.

**Comment by davidlmobley** [comment]
@gduarter - I almost have a fix for all of these. Don't do anything yourself.

**Comment by davidlmobley** [comment]
Marking as closed since I got this in #119.

**Pull request closed without merging**
