### PR TITLE
Implementation of water solvation on gromacs side

### PR DESCRIPTION
**Pull request by davidlmobley**
Addresses same issues as https://github.com/choderalab/openmoltools/pull/116 but with the functionality moved from `utils` into `gromacs`, as well as addition of tests. 

Also at the same time, cleaned up gromacs tests to use amber functionality from `amber` rather than `utils`.

### CODE REVIEW

**Comment by jchodera** [comment]
Do we eventually want to standardize the API for solvation for solvating in multiple codes (gromacs, openmm, LEaP)?  Or is that just going to be impossible since they are so different?

**Comment by davidlmobley** [comment]
As of *right now* this is immensely inconvenient and we have to deal a lot with the differences - *especially* when it comes to water since it gets singled out for "special treatment" as a solvent. I expect as of *very soon*, however, ParmEd is going to make this essentially a non-issue so we can set up using one single tool chain and then just write to whatever format we want. GROMACS writing is already there and about to be released (though I imagine it may need some tweaking to deal with water properly). So very soon I'll be able to get rid of the hack-ish aspects of this and switch to a convenient, unified approach using ParmEd to get to inputs for whatever simulation package we want. 

Hence, I have not paid very much attention here to API standardization since I expect to shortly (perhaps as soon as next week) be able to write a much more general tool which makes most of this obsolete, and I have students who need something functional sooner than that.

**Comment by kyleabeauchamp** [comment]
Code looks reasonable to me, although I haven't used Gromacs 5.0.X extensively.

**Comment by davidlmobley** [comment]
BTW, does anyone know what is up with Travis CI today? The tests just sit there without starting for a very long time (i.e. a couple of hours)...

**Comment by kyleabeauchamp** [comment]
I suppose some days it's just slow due to traffic, some days it's slow due to various hardware failures.  

PS: your current pull request has a bug: you are referencing both `utils.convert_via_acpype`  and `amber.convert_via_acpype`

**Comment by davidlmobley** [comment]
Fixed, thanks. Should be in `utils` since it's not using AMBER tools, but I'd botched this when moving the rest of AMBER-related stuff to `amber`.

**Comment by davidlmobley** [comment]
Passed, merging.

**Pull request merged**
