### PR TITLE
Schrodinger suite wrapper functions and removed logging configuration

### PR DESCRIPTION
**Pull request by andrrizzi**
This PR I have added wrapper functions to Schrodinger's tools ``epik``, ``structconvert``, ``maesubset`` and ``proplister``. I also removed ``logging`` configurations from non-test modules (see #194).

In the last commit, I removed a test for ``enter_temp_directory()`` which is an ``mdtraj`` function, not ``openmoltools``.

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome, thanks!

**Comment by davidlmobley** [comment]
Well, this will be extremely helpful!

**Comment by bas-rustenburg** [comment]
+1. Looks like the tests aren't being skipped on travis though.

**Comment by andrrizzi** [comment]
Ah! Intricacies of nested decorators. It should be fixed now. Waiting for the tests before merging.

**Comment by andrrizzi** [comment]
Looks like tests are passing. Merging.

**Pull request merged**
