### PR TITLE
[WIP] Add a function to create amber topology files

### PR DESCRIPTION
**Pull request by nividic**
This function is slightly different from mixtures. It does not solvate the molecule

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
What is the purpose of this function, as compared to the function for the mixtures?  This needs to be described in the function name or the docstring.

**Comment by davidlmobley** [comment]
OK, I'm not understanding something with GitHub here. For some reason the pull request only shows me that `build_prmtop` was added and only `amber.py` was changed by this PR (which is correct). But I can also see the `do_solvate.py` change in connection with this PR, and if I comment on it the comment shows up here. Weird.

**Comment by nividic** [comment]
In my branch I was creating the do_solvate function. When I pull the request I committed also this function which was not ready yet. I decided to cancel the function and recommit....I'm sorry about that

**Comment by davidlmobley** [comment]
No problem. My comment was more about why GitHub is displaying things the way it is, which in this case is nonintuitive to me.

For the record (for everyone else): We are implementing a test for the new functionality here and then it will probably be ready to merge. The new functionality (`build_prmtop`) handles the case where we simply want AMBER parameter and coordinate files for a single component of a system rather than for a solvated mixture, and is needed for GROMACS workflows coming later. 

I am updating the PR title to include WIP since this is work in progress.

**Comment by nividic** [comment]
Unfortunately, this functionality was already present in the utils.py module and I missed it. It would be better if the functions related to amber are defined in the amber.py  module. As suggest by Dr Mobley we should move the amber functions in the amber.py module and create wrappers in utils.py module to avoid compatibility issues.

**Comment by kyleabeauchamp** [comment]
I think I agree.  I actually have an open issue for this: https://github.com/choderalab/openmoltools/issues/94

In a couple of cases, it's hard to break down some functions by "amber", "openeye", or "utils" because they use multiple tools.

**Comment by jchodera** [comment]
> It would be better if the functions related to amber are defined in the amber.py module. As suggest by Dr Mobley we should move the amber functions in the amber.py module and create wrappers in utils.py module to avoid compatibility issues.

Sounds good.

**Comment by davidlmobley** [comment]
Closing this PR since the functionality was already present in utils.

**Pull request closed without merging**
