### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!

**Comment by jchodera** [comment]
I guess we should add appveyor testing now?

**Comment by rmcgibbo** [comment]
Yeah, still not really ready, but these are simple. No reason to used namedtempfile, since you're in a temp directory already. on windows, the parent needs to close the file handle before the child can start reading it.

**Comment by jchodera** [comment]
Whoops, sorry---I missed the bit where you said "still not ready".

**Comment by jchodera** [comment]
Hopefully it's easy to submit a PR for the remaining bits when done.

**Comment by rmcgibbo** [comment]
No, this is fine. I mean the overall thing. This PR is fine.

**Comment by davidlmobley** [comment]
Thanks, Robert.

—

**Pull request merged**
