### PR TITLE
Fix #271

### LINKED ISSUE #271: generateOEMolFromTopologyResidue sometimes fails on `osx` due to non-UTF-8 character
Sometimes, `generateOEMolFromTopologyResidue` fails on `osx` due to the following error:
```
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/perses-0.1-py3.6.egg/perses/rjmc/topology_proposal.py", line 1236, in build_system
    system = self._forcefield.createSystem(new_topology, **self._forcefield_kwargs)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1123, in createSystem
    if generator(self, res):
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/openmoltools/forcefield_generators.py", line 504, in gaffTemplateGenerator
    molecule = generateOEMolFromTopologyResidue(residue)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/openmoltools/forcefield_generators.py", line 139, in generateOEMolFromTopologyResidue
    [status, output] = getstatusoutput(command)
  File "/Users/choderaj/miniconda/lib/python3.6/subprocess.py", line 517, in getstatusoutput
    data = check_output(cmd, shell=True, universal_newlines=True, stderr=STDOUT)
  File "/Users/choderaj/miniconda/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/choderaj/miniconda/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Users/choderaj/miniconda/lib/python3.6/subprocess.py", line 830, in communicate
    stdout = self.stdout.read()
  File "/Users/choderaj/miniconda/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 34: invalid continuation byte
```
It seems that, on `osx`, this particular file was producing unprintable output that was not `UTF-8`, causing trouble for the `subprocess.getstatusoutput()` call:
```
antechamber -i /var/folders/m1/wl3ptzqx2csf2r_q2bfy78n0h7kcfv/T/tmpn1iljb3r/molecule-before-bond-perception.mol2 -fi mol2 -o /var/folders/m1/wl3ptzqx2csf2r_q2bfy78n0h7kcfv/T/tmpn1iljb3r/molecule-after-bond-perception.ac -fo ac -j 2

Unknown bond type for BOND(C1-N1:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C1-N4:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C1-N5:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C2-N2:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C2-N3:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C2-H1:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C3-C4:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C3-O1:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C3-H2:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C3-H3:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C4-C5:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C4-C9:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C4-H4:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C5-C6:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C5-H5:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C5-H6:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C6-C7:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C6-H7:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C6-H8:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C7-C8:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C7-H9:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C7-H10:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C8-C9:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C8-H11:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C8-H12:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C9-H13:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C9-H14:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C10-C11:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C10-C18:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C10-H15:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C11-C12:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C11-H16:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C12-C13:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C12-H17:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C13-C17:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C13-H18:??TZ?), assuming it is a single bond
Unknown bond type for BOND(N1-C14:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C14-O1:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C14-C15:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C15-N2:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C15-C16:??TZ?), assuming it is a single bond
Unknown bond type for BOND(N3-C16:??TZ?), assuming it is a single bond
Unknown bond type for BOND(N3-H19:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C16-N4:??TZ?), assuming it is a single bond
Unknown bond type for BOND(N5-C17:??TZ?), assuming it is a single bond
Unknown bond type for BOND(N5-H20:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C17-C18:??TZ?), assuming it is a single bond
Unknown bond type for BOND(C18-H21:??TZ?), assuming it is a single bond
```

### PR DESCRIPTION
**Pull request by jchodera**
This fixes #271

### CODE REVIEW

**Comment by jchodera** [comment]
We should probably get this merged.

**Comment by jchodera** [comment]
@lnaden: Could you help with enabling `osx` tests here?

**Comment by jchodera** [comment]
@pgrinaway Looks like tests are re-running. Can you merge when done?

**Comment by jchodera** [comment]
I'm not sure we ever correctly enabled the `osx` tests. Those might have to be fixed separately. There were no `osx` tests previously, which is how this issue cropped up.

**Comment by pgrinaway** [comment]
Yep, I just wanted to see how the tests go before merging.

**Comment by pgrinaway** [comment]
>I'm not sure we ever correctly enabled the osx tests. Those might have to be fixed separately. 

Yeah, I think you're right.

**Comment by ivyzhang999** [comment]
@jchodera  the openmoltools tests are failing on travis (see 1326.2 and 1326.3) and when I run them locally (after merging this commit with master)

**Pull request merged**
